# Generated by Django 3.0.3 on 2020-06-25 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTable',
            fields=[
                ('courseno', models.IntegerField(primary_key=True, serialize=False)),
                ('coursename', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoginTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usrname', models.CharField(max_length=30)),
                ('pas', models.CharField(max_length=40)),
                ('type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='StudentTable',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=40)),
                ('con', models.IntegerField(primary_key=True, serialize=False)),
                ('dob', models.DateField()),
                ('gen', models.CharField(max_length=10)),
                ('usrname', models.CharField(max_length=30)),
                ('pas', models.CharField(max_length=30)),
                ('course', models.ManyToManyField(to='app9.CourseTable')),
            ],
        ),
    ]
